### ISSUE TITLE
Show article description in UI when article is clicked

### ISSUE THREAD

**Issue by j6r** [j6r/IST411#23]
Requirements:

1. Show the article's description when you click on its table row.

2. Remove the description column.

<img width="1059" alt="screen shot 2018-02-09 at 5 18 52 pm" src="https://user-images.githubusercontent.com/32883148/36056945-b0606ea8-0dbd-11e8-95f9-277d8c2e3dde.png">

**Comment by Jaydeboy** [comment]
Completed
