### ISSUE TITLE
Create Bank class

### ISSUE THREAD

**Issue by j6r** [j6r/IST411#6]
The Bank class needs to keep a list of accounts and provide an API to do the following:

- create an account
- get an account's balance
- deposit funds into an account
- withdraw funds from an account
- transfer money between accounts
- close an account

**Comment by Jaydeboy** [comment]
The Account Class were coded with the requested functions.

**Comment by Jaydeboy** [comment]
Bank Class completed

**Comment by Jaydeboy** [comment]
Completed
